[client]
toolbarMode = "viewer"  # Hides developer options for viewers
showErrorDetails = false # Hides technical error traces from users

[browser]
gatherUsageStats = false # Increases privacy
serverAddress = "0.0.0.0"

[theme]
base = "dark"           # Forces Dark Mode (Optional, since we used CSS)
primaryColor = "#FF4B4B"
